version: '3.9'

services:
  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "81:81"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  frontend:
    build: ./frontend
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  backend:
    build: ./backend
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`, `/docs`, `/redoc`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8085"
    environment:
      - DATABASE_URL=postgresql://danaletordaniela:DIAmond2018!@localhost:5432/mydatabase


  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: danaletordaniela
      POSTGRES_PASSWORD: DIAmond2018!
      POSTGRES_DB: mydatabase

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    labels:
      - "traefik.http.routers.adminer.rule=Host(`db.domain`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    ports:
      - "8090:8090"
    labels:
      - "traefik.http.routers.proxy-manager.rule=Host(`proxy.domain`)"
      - "traefik.http.services.proxy-manager.loadbalancer.server.port=8090"

